const stepsData = [
{ level: "1", name: "pas bàsic", description: "pas doblats" },
{ level: "1", name: "canvi de lloc", description: "" },
{ level: "1", name: "volta noia", description: "" },
{ level: "1", name: "volta noi", description: "" },
{ level: "1", name: "rascar esquena", description: "volta noi" },
{ level: "1", name: "volta doble", description: "" },
{ level: "1", name: "canvi de mà", description: "amb volta noia" },
{ level: "1", name: "canvi de mà", description: "amb volta noi pel darrere" },
{ level: "1", name: "canvi de mà", description: "sense volta noia" },
{ level: "1", name: "pas de costat", description: "" },
{ level: "1", name: "volta tots dos", description: "" },
{ level: "1", name: "volta noi seguit de volta noia", description: "volta noi temps 2 seguit de volta noia temps 4" },
{ level: "1", name: "cargolar noia al costat", description: "sortida amb una mà" },
{ level: "1", name: "cargolar noia al costat", description: "sortida dues mans" },
{ level: "1", name: "tibar recollir sortir", description: "*" },
{ level: "1", name: "passada per l'esquerra", description: "" },
{ level: "1", name: "tibar mà creuada", description: "(todousos) noia darrere" },
{ level: "1", name: "tibar mà creuada", description: "(todousos) noia a prop" },
{ level: "1", name: "tibar mà creuada", description: "(todousos) buscant la noia" },
{ level: "1", name: "pessigar el braç", description: "" },
{ level: "1", name: "llaç", description: "des de mà creuada" },
{ level: "1", name: "volta noia to alt", description: "" },
{ level: "1", name: "tibar amb passets", description: "" },
{ level: "1", name: "volta complicada", description: "" },
{ level: "1", name: "volta complicada mà creuada", description: "" },
{ level: "1", name: "passets des de tibar", description: "des de mà creuada" },
{ level: "1", name: "volta complicada + passets mà creuada", description: "" },
{ level: "1", name: "la porta del metro", description: "" },
{ level: "1", name: "volta noia to alt creuant mà", description: "" },
{ level: "1", name: "volta noia to baix", description: "" },
{ level: "1", name: "volta noia to baix creuant mà", description: "" },
{ level: "2", name: "triple plas", description: "(pas bàsic)" },
{ level: "2", name: "l'agafada mà creuada", description: "" },
{ level: "2", name: "l'agafada mà creuada amb volta noi", description: "" },
{ level: "2", name: "(variació todousos) passar noia darrera amb seqüència noia/noi i sortida noia (autobus)", description: "" },
{ level: "2", name: "cargolar sense canviar direcció noia", description: "" },
{ level: "2", name: "io-io", description: "sortida deixant-la anar" },
{ level: "2", name: "io-io", description: "sortida amb mà acompanyada" },
{ level: "2", name: "io-io", description: "sortida frenant i voltant noia" },
{ level: "2", name: "passada per l'esquerra", description: "amb volta contra horària" },
{ level: "2", name: "passada per l'esquerra", description: "amb volta contra horària des de mà creuada" },
{ level: "2", name: "cargolar costat esquerra", description: "desenvolupan volta" },
{ level: "2", name: "cargolar costat esquerra", description: "desenvolupan volta mà creuada" },
{ level: "2", name: "passets amb mà creuada", description: "des de volta complicada" },
{ level: "2", name: "volta noia passant per davant des de mà dreta", description: "*" },
{ level: "2", name: "rascar esquena doble", description: "doble volta noi" },
{ level: "2", name: "passets mà creuada sentit horari", description: "sortida amb volta noia" },
{ level: "2", name: "todousos", description: "" },
{ level: "2", name: "ganxo (des de doble dobla volta noi rascant esquena)", description: "des de todousos" },
{ level: "2", name: "passets doblats", description: "" },
{ level: "2", name: "palanca i canvi", description: "" },
{ level: "2", name: "amago volta noia to alt fent volta contrària i passos fins 9&10", description: "passos fins temps 9-10" },
{ level: "2", name: "contra parada", description: "" },
{ level: "2", name: "salt mà panxa", description: "" },
{ level: "2", name: "mig remolí", description: "semblant porta del metro passant mà pel darrere esquena" },
{ level: "3", name: "canvi mà/to amb volta noia to alt", description: "repàs rock 2" },
{ level: "3", name: "passets doblats", description: "repàs rock 2" },
{ level: "3", name: "palanca i canvi", description: "repàs rock 2" },
{ level: "3", name: "contraparada volta esquerra", description: "passos fins temps 9-10" },
{ level: "3", name: "dobla volta noi rascar esquena", description: "repàs rock 2" },
{ level: "3", name: "ganxo", description: "des de rascar esquena doble" },
{ level: "3", name: "contraparada volta dreta", description: "amb diferents mans*" },
{ level: "3", name: "embolic", description: "passos fins 1-6; continuació fins 1-10" },
{ level: "3", name: "parada al 2", description: "i reenganxar 1-2..." },
{ level: "3", name: "molintes", description: "passos fins a temps 1-10" },
{ level: "3", name: "mig remolí", description: "repàs rock 2" },
{ level: "3", name: "salt de la noia amb mà a la cadera", description: "" },
{ level: "3", name: "mà al cul", description: "passant braç per sobre" },
{ level: "3", name: "mà al cul", description: "passant braç per sota" },
{ level: "3", name: "mà a la cintura", description: "fent gir a la noia" },
{ level: "3", name: "mà a la cintura", description: "fent gir a la noia amb dues mans" },
{ level: "3", name: "agafada des de mà creuada", description: "introducció per a la següent figura" },
{ level: "3", name: "bloqueig espatlles amb passets", description: "sortida temps 5-6" },
{ level: "3", name: "bloqueig espatlles amb passets", description: "sortida 3-4 amb passos fins 5-6" },
{ level: "3", name: "cestita", description: "passets des de mà creuada a l'espatlla d'ella" },
{ level: "3", name: "cestita", description: "sortida estil molinets" },
{ level: "4", name: "Passets des de todousos amb passets doblats", description: "repàs rock 3" },
{ level: "4", name: "Tobogan passant mà noi per sobre del cap", description: "" },
{ level: "4", name: "Tobogan deixant mà noi a l'espatlla", description: "sortida Todousos o sortida Ganxo" },
{ level: "4", name: "Variacions todousos fent passar ella davant aixecant braç dret", description: "" },
{ level: "4", name: "Variacions todousos fent passar ella darrera passant davant fent gir", description: "" },
{ level: "4", name: "Variacions todousos fent sortir ella del darrera fent volta amb braç esquerra", description: "" },
{ level: "4", name: "70 variat", description: "" },
{ level: "4", name: "reverència", description: "" },
{ level: "4", name: "venint passets mà creuada; fer molinet i passar davant", description: "" },
{ level: "4", name: "Batuda + salt noia", description: "" },
{ level: "4", name: "Break amb caiguda (7-8)", description: "" },
{ level: "4", name: "Volta noia per l'altra banda (mà creuada, carril esquerra + mitja volta noi)", description: "" },
{ level: "4", name: "Botifarra", description: "" },
{ level: "4", name: "Bloqueig + doble canvi posició (des de mà creuada)", description: "" },
{ level: "4", name: "Bloqueig + doble canvi posició + volta noia", description: "" },
{ level: "4", name: "Bloqueig + doble canvi posició + volta noia: variació amb volta noi horari", description: "" },
{ level: "4", name: "Bloqueig + doble canvi posició + volta noia: variació amb volta noi contra horari (Patrici)", description: "" },
{ level: "4", name: "Doble cargolada (noi aixecar braç esquerra per a la seva direcció de volta, queda al costat then pas enrera per passar-al de costat i desfer amb volta)", description: "" },
{ level: "4", name: "doble volta noia", description: "" },
{ level: "4", name: "Doble cargolar", description: "" }
];
